[build]
  command = "npm install"
  # Change this to "." if you want the root to be the publish directory
  publish = "." 

[functions]
  external_node_modules = ["@xenova/transformers", "@lancedb/lancedb"]

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/mcp"
  status = 200